(()=>{
if(!document.getElementById('dtd-music-pill')){
 const AUDIO_URL='https://www.marineband.marines.mil/Portals/175/Docs/Audio/Complete%20Marches%20of%20JPS/Volume%202/34%20Semper%20Fidelis.mp3';
 const style=document.createElement('style');style.textContent=`#dtd-music-pill{position:fixed;left:16px;bottom:16px;z-index:9997;display:flex;align-items:center;gap:10px;max-width:calc(100% - 200px);background:#07111bee;color:#fff;border:1px solid #d9b45a;border-radius:999px;padding:8px 10px 8px 14px;box-shadow:0 8px 30px rgba(0,0,0,.35);font-family:Arial,sans-serif}#dtd-music-pill .dtd-music-label{min-width:0;font-size:12px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#dtd-music-pill button{border:0;border-radius:999px;background:#d9b45a;color:#07111b;font-weight:900;min-height:38px;padding:8px 12px;cursor:pointer}#dtd-music-pill .dtd-music-status{font-size:10px;color:#d7e2ea;display:block;margin-top:1px}@media(max-width:560px){#dtd-music-pill{left:10px;bottom:10px;max-width:58%}}`;document.head.appendChild(style);
 const wrap=document.createElement('div');wrap.id='dtd-music-pill';wrap.innerHTML=`<div class="dtd-music-label">♪ Semper Fidelis — U.S. Marine Band<span class="dtd-music-status">Paused</span></div><button type="button">▶ Play</button>`;document.body.appendChild(wrap);
 const button=wrap.querySelector('button'),status=wrap.querySelector('.dtd-music-status'),audio=new Audio(AUDIO_URL);audio.preload='none';button.addEventListener('click',async()=>{if(audio.paused){try{await audio.play();button.textContent='⏸ Pause';status.textContent='Playing on DogTagDay.org'}catch(e){status.textContent='Unable to play audio'}}else{audio.pause();button.textContent='▶ Play';status.textContent='Paused'}});audio.addEventListener('ended',()=>{button.textContent='▶ Play';status.textContent='Paused'});audio.addEventListener('error',()=>{button.textContent='▶ Play';status.textContent='Audio unavailable'});
}
const outreach=document.getElementById('outreach'),support=document.getElementById('support');
if(outreach&&support){support.parentNode.insertBefore(outreach,support);outreach.style.background='linear-gradient(180deg,#020406,#09111a 54%,#020406)';outreach.style.padding='42px 0 22px';const intro=outreach.querySelector('.map-intro');if(intro){intro.innerHTML='<p class="eyebrow">Outreach Across America</p><h2>1,850+ Outreach Lights</h2><p>A giant golden view of Dog Tag Day outreach across America, with color-coded outreach categories.</p>'}const frame=outreach.querySelector('iframe');if(frame){frame.src='map-golden-1850.html?v=20260830GOLD1850';frame.title='Dog Tag Day giant golden 1,850-plus outreach map';frame.style.height='min(76vw,820px)';frame.style.minHeight='430px';frame.style.background='#020406'}const wrap=outreach.querySelector('.map-wrap');if(wrap){wrap.style.maxWidth='1500px';wrap.style.width='96%';wrap.style.border='2px solid #d9b45a';wrap.style.borderRadius='20px';wrap.style.overflow='hidden';wrap.style.boxShadow='0 0 38px rgba(217,180,90,.22)'}}
const hero=document.querySelector('.hero-frame');if(hero&&!document.getElementById('dtd-seasonal-accent')){const now=new Date(),y=now.getFullYear(),labor=new Date(y,8,1);labor.setDate(1+(8-labor.getDay())%7);const active=(now>=new Date(y,8,1)&&now<new Date(y,8,labor.getDate()+1))||(y===2026&&now>=new Date(2026,7,30)&&now<new Date(2026,8,8));if(active){hero.style.position='relative';const hs=document.createElement('style');hs.textContent=`#dtd-seasonal-accent{position:absolute;top:8px;right:8px;width:clamp(62px,8vw,108px);z-index:12;filter:drop-shadow(0 5px 8px rgba(0,0,0,.55));pointer-events:none}#dtd-seasonal-accent svg{display:block;width:100%}`;document.head.appendChild(hs);const a=document.createElement('div');a.id='dtd-seasonal-accent';a.setAttribute('aria-label','Labor Day patriotic star and ribbon');a.innerHTML=`<svg viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#fff2b3"/><stop offset=".3" stop-color="#d9b45a"/><stop offset=".62" stop-color="#8f6a1f"/><stop offset="1" stop-color="#f7dc86"/></linearGradient></defs><path d="M41 49 31 106 47 95 58 110 64 53Z" fill="#b31f2c"/><path d="M79 49 89 106 73 95 62 110 56 53Z" fill="#244e7d"/><path d="M55 51 52 106 60 98 68 106 65 51Z" fill="#f5f2e8"/><polygon points="60,9 72,43 108,43 79,64 90,99 60,78 30,99 41,64 12,43 48,43" fill="url(#g)" stroke="#fff0b0" stroke-width="1.4"/></svg>`;hero.appendChild(a)}}
const duplicate=document.getElementById('supportDogTagDay');if(duplicate)duplicate.remove();
})();